RPN-513: get creator from opensea lazymint
rarible/ethereum-indexer pull request #14
Opened 2021-08-23 08:06 UTC by mystdeim

2021-08-23 15:59 UTC, evgenynacu requested changes

2021-08-23 15:59 UTC, evgenynacu commented on nft/api/src/main/resources/config/application.yml
> +  openseaLazyMintAddress: "0x495f947276749ce646f68ac8c248420045cb7b5e"
this should go in env specific config I think

2021-08-23 15:59 UTC, evgenynacu commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/item/ItemCreatorService.kt
> +        itemCreatorRepository.save(ItemCreator(itemId, creator))
this way it won't work. when you do this, nothing will be changed. you have to subscribe to Mono

2021-08-23 15:59 UTC, evgenynacu commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/item/ItemCreatorService.kt
> +        val creator = Address.apply(tokenId.value.toByteArray().copyOfRange(0, 20))
That's not a correct way to transform BigInteger to byte array. use Uint256Type

2021-08-24 07:42 UTC, sanufriev commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/item/ItemCreatorService.kt
> +    @Value("\${common.openseaLazyMintAddress}") private val openseaLazyMint: String
We don't use @Value in code, please use NftIndexerProperties injection

2021-08-24 07:42 UTC, sanufriev commented on nft/api/src/main/resources/config/application.yml
> +  openseaLazyMintAddress: "0x495f947276749ce646f68ac8c248420045cb7b5e"
It better to define it in prod profile config.
And what about dev/e2e configs?

2021-08-24 08:16 UTC, merged