RPN-1402
rarible/ethereum-indexer pull request #152
Opened 2021-11-30 12:55 UTC by mystdeim

2021-11-30 15:34 UTC, serejke requested changes

2021-11-30 15:34 UTC, serejke commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/model/OrderStatus.kt
> +    NOT_STARTED,
The model becomes more complex, so we seem to need Javadoc for all these fields: how an when the transition is made from one status to another.

2021-11-30 15:34 UTC, serejke commented on order/listener/src/test/kotlin/com/rarible/protocol/order/listener/service/order/OrderStartEndCheckerTest.kt
> +        check(orderVersion.hash, OrderStatus.NOT_STARTED)
AFAIU, the `NOT_STARTED` state is an intermediate state, it must become the ACTIVE order at some point.
This test does not check it.

2021-11-30 15:34 UTC, serejke commented on order/listener/src/main/kotlin/com/rarible/protocol/order/listener/job/OrderStartEndCheckerJob.kt
> +            orderRepository.save(order)
This is non-obvious what happens here. For an new developer it looks like "read from repo, write to repo"

You rely on the fact that mongo deserializer in the `findExpiredOrders`/`findAliveOrders` calls `init` that calls `calculateStatus`.
Let's make this logic explicit, for instance explicitly call `order.copy()` here and add a Javadoc, or introduce a new method `Order.withUpdatedStatus()` that does exactly the same.

2021-11-30 15:34 UTC, serejke commented on order/listener/src/main/kotlin/com/rarible/protocol/order/listener/job/OrderStartEndCheckerJob.kt
> +            orderRepository.save(order)
We used to update make stock here. Who will do it now for non-active/activated orders?

2021-11-30 15:34 UTC, serejke commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +                Order::status isEqualTo OrderStatus.ACTIVE,
You check only the ACTIVE status, but you introduced NOT_STARTED status - it must be requested too.

Or maybe I don't understand the meaning of NOT_STARTED - for me it looks like an intermediate status that later will become ACTIVE or INACTIVE/ENDED

2021-11-30 16:07 UTC, mystdeim commented on order/listener/src/main/kotlin/com/rarible/protocol/order/listener/job/OrderStartEndCheckerJob.kt
> +            orderRepository.save(order)
fixed

2021-12-01 06:32 UTC, serejke commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/model/OrderStatus.kt
> +     * order doesn't match start, end interval && makeStock == 0
This is not only about orders that don't match start/end, but also about those with makeStock == 0,
rephrase it

2021-12-01 11:52 UTC, sanufriev commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/model/Order.kt
> +                makeStock > EthUInt256.ZERO && isAlive(start, end) -> OrderStatus.ACTIVE
I think if makeStock == EthUInt256.ZERO and !isStarted(start) order status will be OrderStatus.NOT_STARTED, is is correct?

2021-12-01 11:52 UTC, sanufriev commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +    fun findAliveOrders(now: Instant): Flow<Order> {
Maybe rename method?

2021-12-01 11:56 UTC, mystdeim commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/model/Order.kt
> +                makeStock > EthUInt256.ZERO && isAlive(start, end) -> OrderStatus.ACTIVE
Yes, if !isStarted(start) status will be OrderStatus.NOT_STARTED. It doesn't matter makeStock == EthUInt256.ZERO or not

2021-12-01 11:57 UTC, mystdeim commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +    fun findAliveOrders(now: Instant): Flow<Order> {
`findStarted` or which name is better?

2021-12-01 12:36 UTC, serejke requested changes

2021-12-01 12:36 UTC, serejke commented on order/migration/src/main/kotlin/com/rarible/protocol/order/migration/mongock/mongo/ChangeLog00014RecalculateMakeStock.kt
> +                val order = orderUpdateService.updateMakeStock(order.hash)
We need to compare with previous makeStock (before update), to exclude orders for which makeStock did not change

2021-12-01 12:36 UTC, serejke commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/model/Order.kt
> +        return copy(status = calculateStatus(fill, take, makeStock, cancelled, start, end))
It is enough to do just `copy()` - it will recalculate the makeStock in constructor.

2021-12-01 12:37 UTC, serejke commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +    fun findAliveOrders(now: Instant): Flow<Order> {
`findNotStarted` as the status implies.

2021-12-01 14:53 UTC, mystdeim commented on order/migration/src/main/kotlin/com/rarible/protocol/order/migration/mongock/mongo/ChangeLog00014RecalculateMakeStock.kt
> +                val order = orderUpdateService.updateMakeStock(order.hash)
fixed

2021-12-06 06:23 UTC, merged