RPN-1360: meta for collection
rarible/ethereum-indexer pull request #155
Opened 2021-12-06 08:51 UTC by mystdeim

2021-12-06 11:00 UTC, serejke requested changes

2021-12-06 11:00 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/model/TokenMeta.kt
> +    val fee_recipient: Address?,
`recipientFee` is better

2021-12-06 11:00 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/TokenListener.kt
> +            collection = collectionDtoConverter.convert(ExtendedToken(token, meta))
We don't want to request meta in the block processor - it may take significant type and slow down the token processing. Please read how it is done for item's meta and repeat the same.
There we have an internal queue, to which the reducer puts an item (without meta), and later nft-listener has a ConsumerWorker job pulling off the items from that internal queue, requesting meta, attaching it to the item and sending full Kafka events.

2021-12-06 11:00 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/meta/descriptors/StandardDescriptor.kt
> +            else -> Mono.empty()
Please add @SuppressedWarning to avoid highlighting in this line

2021-12-06 11:00 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/meta/descriptors/OpenseaDescriptor.kt
> +        logger.info("OpenSea: getting properties from $httpUrl")
Please add `logTokenProperties` utility (similar to `logProperties` for item metadata) , which makes `log.info` with the same prefix. This is convenient to see logs having the same prefix

2021-12-06 11:00 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/meta/descriptors/OpenseaDescriptor.kt
> +        private fun createConnector(
Copy paste from the `OpenSeaPropertiesResolver`

2021-12-06 11:00 UTC, serejke commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/collection/CollectionMetaFt.kt
> +    @SpyBean
Please don't use @MockkBean and @SpyBean in integration tests - it is unpredictable whether Spring will reuse the test context or create a new. And our infrastructure is not ready for 2 active contexts at the same time.

Instead, in the `@TestConfiguration` declare a mocked bean for the descriptor, and in here inject using @Qualifier("mockTokenPropertiesResolver")

See an example for `@Qualifier("mockItemPropertiesResolver")`

2021-12-06 11:00 UTC, serejke commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/collection/CollectionMetaFt.kt
> +        userSender = MonoSigningTransactionSender(
Move this as `createSender` utility method to the base class, how it is done in other modules in the `AbstractIntegrationTest`s

2021-12-06 11:00 UTC, serejke commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/collection/CollectionMetaFt.kt
> +        setField(standardDescriptor, "client", mockSuccessIpfsResponse())
Avoid using reflection in tests. We spent several hours debugging a problem with reflection used upon proxied bean (by APM) 

I suggested to declare a mocked Resolver , and here you can just do `coEvery { ... }` on it

2021-12-08 07:13 UTC, serejke requested changes

2021-12-08 07:13 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/converters/dto/NftCollectionMetaDtoConverter.kt
> +            name = source.properties?.name,
This can't be null, the file is full of warnings

2021-12-08 07:13 UTC, serejke commented on nft/listener/src/main/kotlin/com/rarible/protocol/nft/listener/configuration/NftListenerConfiguration.kt
> +        logger.info("Creating batch of ${nftIndexerProperties.nftCollectionMetaExtenderWorkersCount} item meta extender workers")
"item" -> "collection"

2021-12-08 07:13 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/producer/ProtocolNftEventPublisher.kt
> +    private val internalCollectionEventsProducer: RaribleKafkaProducer<NftCollectionEventDto>,
Forgot to add bean for internal collection producer RaribleKafkaProducer<> - there is only one for public collection events.

See `ProducerFactory#createInternalItemEventsProducer`, do the same for collection

2021-12-08 07:13 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/meta/TokenMetaService.kt
> +        val properties = tokenPropertiesService.resolve(id)
check that properties == null and return immediately, this is hard to read `?. ?: Token.EMPTY`

2021-12-08 07:13 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/meta/TokenMetaService.kt
> +            properties = TokenProperties(
Why do you copy `it` to the same new object? Just use the `it` immediately.

2021-12-08 07:15 UTC, serejke commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/integration/TestPropertiesConfiguration.kt
> +
Forgot to add 
`fun collectionMetaExtenderWorkerStarter` as below

2021-12-08 07:20 UTC, serejke commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/SpringContainerBaseTest.kt
> +    @Qualifier("mockStandardPropertiesResolver")
Add "token" word here and in all similar places

2021-12-08 16:31 UTC, mystdeim commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/meta/descriptors/OpenseaPropertiesResolver.kt
> +        val node = mapper.readTree(jsonBody) as ObjectNode
It's handled by `.onErrorResume` in the invoking method

2021-12-09 12:56 UTC, serejke commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/service/token/TokenUpdateServiceTest.kt
> +            println(ObjectMapper().writeValueAsString(collectionEvents))
Letfover

2021-12-09 12:56 UTC, serejke commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/service/token/TokenUpdateServiceTest.kt
> +            assertThat(collectionEvents).anyMatch {
add utility method for checking collection activity in the AbstractIntegrationTest, similar to `checkItemEventWasPublished`

2021-12-09 12:56 UTC, serejke commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/integration/AbstractIntegrationTest.kt
> +    protected val collectionEvents = CopyOnWriteArrayList<NftCollectionEventDto>()
make private after adding a utility method (see below)

2021-12-09 12:56 UTC, serejke commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/integration/AbstractIntegrationTest.kt
> +        collectionEvents.clear()
will be unnecessary, because each test creates a new object

2021-12-09 12:56 UTC, serejke commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/service/token/meta/StandardTokenPropertiesResolverTest.kt
> +class StandardTokenPropertiesResolverTest : AbstractIntegrationTest() {
I'm afraid we don't want this test to be run automatically because it requires internet connection.

There is `@ItemMetaTest` annotation for item tests, let's mark these tests with it too, to run only if the system property is specified.

2021-12-09 12:56 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/service/token/meta/descriptors/StandardTokenPropertiesResolver.kt
> +    protected val client = WebClient.builder().apply {
We need to use the `ExternalHttpClient` here as well (inject via constructor) because in general the URL of the contract meta may point to OpenSea's API and we need to use a proxy

2021-12-09 12:56 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/misc/OpenSea.kt
> +package com.rarible.protocol.nft.core.misc
This file is not needed anymore

2021-12-09 15:51 UTC, mystdeim commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/service/token/meta/StandardTokenPropertiesResolverTest.kt
> +class StandardTokenPropertiesResolverTest : AbstractIntegrationTest() {
No, it works without the internet connection. There's a mock for http client

2021-12-10 05:21 UTC, serejke commented
Approved! 🎉

2021-12-10 06:55 UTC, merged