feat: Correct handling for base64 data in meta urls
rarible/ethereum-indexer pull request #223
Opened 2022-02-04 12:47 UTC by yakischik

2022-02-06 15:57 UTC, serejke requested changes

2022-02-06 15:57 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/converters/dto/NftItemMetaDtoConverter.kt
> +    private fun ItemProperties.toUrlMap(
Let's reuse this function for 'animation' as well and remove function duplication

2022-02-06 15:57 UTC, serejke commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/converters/dto/NftItemMetaDtoConverterTest.kt
> +        assertThat(result.name).isEqualTo(meta.properties.name)
Let's please compare the whole expected object, not individual fields, such a test will be easier to read.

2022-02-06 15:57 UTC, serejke commented on nft/listener/src/main/kotlin/com/rarible/protocol/nft/listener/admin/descriptor/AdminErc721TransferLogDescriptor.kt
>      NftIndexerProperties(
Here we can pass only the `ScannerProperties` to the `TransferLogDescriptor` and remove dummy initialization of 100500 fields of `NftIndexerProperties`.

2022-02-06 15:57 UTC, serejke commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/misc/Base64Detector.kt
> +    private val url: String
Let's move `url` to function's parameters. Such API is not very common.
I would prefer to have Base64Detector be an `object` and have 1 method `fun detect(url: String): Base64DetectResult { }` where 
`sealed class Base64DetectResult` with 
`data class Base64(val data: String, val mimeType: String) : Base64DetectResult()` and 
`object NotBase64 : Base64DetectResult()`

2022-02-06 15:57 UTC, serejke commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/controller/ItemController.kt
> +        val itemMeta = withContext(NonCancellable) {
Why is `NonCancellable` needed here?

2022-02-07 07:29 UTC, yakischik commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/converters/dto/NftItemMetaDtoConverter.kt
> +    private fun ItemProperties.toUrlMap(
In such case we need to add one more endpoint to retrieve animation or extend its parameters. I think in case of animation there can't be base64 values

2022-02-07 07:31 UTC, yakischik commented on nft/core/src/test/kotlin/com/rarible/protocol/nft/core/converters/dto/NftItemMetaDtoConverterTest.kt
> +        assertThat(result.name).isEqualTo(meta.properties.name)
This is converter test, so i compare fields of different objects. If i want to compare entire objects, i have to convert it to the same type - but such conversion is a function we are testing in the test

2022-02-07 07:32 UTC, yakischik commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/misc/Base64Detector.kt
> +    private val url: String
In such case we need to perform same operations with string like indexOf several times

2022-02-07 07:33 UTC, yakischik commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/controller/ItemController.kt
> +        val itemMeta = withContext(NonCancellable) {
Have no idea, the same thing done for getMeta, so i used same approach here

2022-02-07 07:39 UTC, yakischik commented on nft/listener/src/main/kotlin/com/rarible/protocol/nft/listener/admin/descriptor/AdminErc721TransferLogDescriptor.kt
>      NftIndexerProperties(
This should be fixed in regular tech-debt issue, not in a patch

2022-02-07 07:43 UTC, merged