RPN-933
rarible/ethereum-indexer pull request #27
Opened 2021-09-01 19:55 UTC by mystdeim

2021-09-02 11:01 UTC, serejke requested changes

2021-09-02 11:01 UTC, serejke commented on nft/migration/src/test/java/com/rarible/protocol/nft/migration/CreateAttributes.kt
> +fun main() {
is this file needed? maybe it's used for local experiments?

2021-09-02 11:01 UTC, serejke commented on nft/migration/src/test/java/com/rarible/protocol/nft/migration/integration/TestPropertiesConfiguration.kt
> +            propertiesCacheDescriptor,
I guess you can `mockk()` out all these descriptors

2021-09-02 11:26 UTC, mystdeim commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/repository/item/ItemPropertyRepository.kt
> +    fun get(itemId: ItemId): Mono<String> {
Just don't want to add implicit logic for duration into `get(itemId, timeToLive)`

2021-09-02 11:26 UTC, mystdeim commented on nft/core/src/main/kotlin/com/rarible/protocol/nft/core/repository/item/ItemPropertyRepository.kt
> +    fun count(): Mono<Long> {
Removed

2021-09-02 11:27 UTC, mystdeim commented on nft/migration/src/test/java/com/rarible/protocol/nft/migration/CreateAttributes.kt
> +fun main() {
removed the file

2021-09-02 11:27 UTC, mystdeim commented on nft/migration/src/test/java/com/rarible/protocol/nft/migration/integration/TestPropertiesConfiguration.kt
> +            propertiesCacheDescriptor,
fixed

2021-09-02 11:28 UTC, mystdeim commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/ItemPropertiesService.kt
> +    private val itemPropertiesRepository: ItemPropertyRepository,
Eugene wanted to simplify a getting meta process for punks.

2021-09-03 06:34 UTC, serejke approved these changes

2021-09-05 16:03 UTC, serejke commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/ItemPropertiesService.kt
> +    private val itemPropertiesRepository: ItemPropertyRepository,
I mean to keep the approach but sintatically move code to a dedicated class, to reduce clutter in the ItemPropertiesService

2021-09-13 09:43 UTC, merged