RPN-888: add base64 extration & fix traits
rarible/ethereum-indexer pull request #34
Opened 2021-09-07 11:14 UTC by mystdeim

2021-09-08 15:28 UTC, serejke commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/PropertiesCacheDescriptor.kt
> +            logger.info("Decoding properties from base64")
Add 'str' to the log message?

2021-09-08 15:28 UTC, serejke commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/PropertiesCacheDescriptor.kt
> +        return mono {
`parse(str).toMono()` instead of `mono { ... }`

2021-09-08 15:28 UTC, serejke commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/Utils.kt
> +fun JsonNode.toProperties(): List<ItemAttribute> {
I would keep this function (as `private`) in the `PropertiesCacheDescriptor`, because this is the only place where it is used

2021-09-08 15:28 UTC, serejke commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/meta/StandartPropertiesExtractionIt.kt
> +        val nonce = SignUtils.sign(privateKey, tokenId, contract.address())
this is `signature` not `nonce`

2021-09-08 15:28 UTC, serejke commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/meta/StandartPropertiesExtractionIt.kt
> +    @MockBean
There is already `@MockkBean` annotation from another mocking library `springmockk` available in test sources,
let's not introduce a new dependency `mockito-kotlin`
See an example at `OrderRepositoryIt.should save order and publish change event`

2021-09-08 15:28 UTC, serejke commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/meta/StandartPropertiesExtractionIt.kt
> +        Mockito.`when`(openseaClient.fetchAsset(isA(), isA()))
With another mocking library it will be something like
`every { openseaClient.fetchAsset(any(), any()) } returns Mono.empty<ItemProperties>()`

2021-09-08 15:28 UTC, serejke commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/PropertiesCacheDescriptor.kt
> +    fun parse(body: String): ItemProperties {
should be `private`

2021-09-08 19:11 UTC, mystdeim commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/PropertiesCacheDescriptor.kt
> +            logger.info("Decoding properties from base64")
fixed

2021-09-08 19:11 UTC, mystdeim commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/PropertiesCacheDescriptor.kt
> +        return mono {
fixed

2021-09-08 19:12 UTC, mystdeim commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/Utils.kt
> +fun JsonNode.toProperties(): List<ItemAttribute> {
It's also used in the Opensea client

2021-09-08 19:12 UTC, mystdeim commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/meta/StandartPropertiesExtractionIt.kt
> +        val nonce = SignUtils.sign(privateKey, tokenId, contract.address())
fixed

2021-09-08 19:13 UTC, mystdeim commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/meta/StandartPropertiesExtractionIt.kt
> +    @MockBean
thanks, don't about this annotation, fixed

2021-09-08 19:13 UTC, mystdeim commented on nft/api/src/test/kotlin/com/rarible/protocol/nft/api/e2e/meta/StandartPropertiesExtractionIt.kt
> +        Mockito.`when`(openseaClient.fetchAsset(isA(), isA()))
fixed

2021-09-09 08:58 UTC, serejke requested changes

2021-09-09 08:58 UTC, serejke commented on nft/api/src/main/kotlin/com/rarible/protocol/nft/api/service/item/meta/LootCacheDescriptor.kt
> +    override val collection: String = "cache_properties"
It must be `"cache_loot"`, see example in `WaifusionCacheDescriptor` and other descriptors

2021-09-22 09:30 UTC, merged