RPN-891: supporting start & end in the orders
rarible/ethereum-indexer pull request #55
Opened 2021-09-17 14:19 UTC by mystdeim

2021-09-24 09:56 UTC, yakischik requested changes

2021-09-24 09:56 UTC, yakischik commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/model/Order.kt
> +        private fun active(start: Long?, end: Long?): Boolean {
Maybe isAlive?

2021-09-24 09:56 UTC, yakischik commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +        return template.updateFirst(query, Update().set("makeStock", EthUInt256.ZERO), Order::class.java)
Order::makeStock.name is preferable than literals

2021-09-24 09:56 UTC, yakischik commented on order/listener/src/main/kotlin/com/rarible/protocol/order/listener/job/OrderRecalculateMakeStockJob.kt
> +        logger.info("Starting update...")
In logs it is better to write more specific messages like "Starting to update makeStock for orders"

2021-09-24 09:56 UTC, yakischik commented on order/listener/src/main/kotlin/com/rarible/protocol/order/listener/job/OrderRecalculateMakeStockJob.kt
> +        logger.info("Successfully finished update().")
The same - a bit more detailed message

2021-09-24 09:56 UTC, yakischik commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +    fun resetMakeStockAfter(now: Instant): Mono<UpdateResult> {
Do we have index for such query?

2021-09-24 09:56 UTC, yakischik commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +    fun findActualZeroMakeStock(now: Instant): Flow<Order> {
Do we have index for such query?

2021-09-27 06:57 UTC, mystdeim commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/model/Order.kt
> +        private fun active(start: Long?, end: Long?): Boolean {
renamed

2021-09-27 06:57 UTC, mystdeim commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +        return template.updateFirst(query, Update().set("makeStock", EthUInt256.ZERO), Order::class.java)
fixed

2021-09-27 06:57 UTC, mystdeim commented on order/listener/src/main/kotlin/com/rarible/protocol/order/listener/job/OrderRecalculateMakeStockJob.kt
> +        logger.info("Successfully finished update().")
fxied

2021-09-27 06:58 UTC, mystdeim commented on order/listener/src/main/kotlin/com/rarible/protocol/order/listener/job/OrderRecalculateMakeStockJob.kt
> +        logger.info("Starting update...")
added more text

2021-09-27 06:58 UTC, mystdeim commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +    fun resetMakeStockAfter(now: Instant): Mono<UpdateResult> {
added index

2021-09-27 06:58 UTC, mystdeim commented on order/core/src/main/kotlin/com/rarible/protocol/order/core/repository/order/MongoOrderRepository.kt
> +    fun findActualZeroMakeStock(now: Instant): Flow<Order> {
added index

2021-09-27 07:25 UTC, yakischik approved these changes

2021-09-27 07:39 UTC, merged