Pt 3597
rarible/ethereum-indexer pull request #737
Opened 2023-08-25 11:45 UTC by sanufriev

2023-08-25 12:07 UTC, dmitry-saraykin approved these changes

2023-10-04 07:42 UTC, dmitry-saraykin approved these changes

2023-10-04 13:12 UTC, alexbukata requested changes

2023-10-04 13:12 UTC, alexbukata commented on nft/api/src/main/resources/config/application-ethereum-dev.yml
> +  chainId: 300500
было 3 стало 300500?

2023-10-04 14:38 UTC, sanufriev commented on nft/api/src/main/resources/config/application-ethereum-dev.yml
> +  chainId: 300500
Да, 3 это не верное значение, верное было в консуле

2023-10-06 09:16 UTC, merged